# Generated by Django 2.0.7 on 2018-07-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='trip_type',
            field=models.IntegerField(choices=[(1, 'trip1'), (2, 'trip2')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='trip_type',
            field=models.IntegerField(choices=[(1, 'trip1'), (2, 'trip2')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('group', 'user', 'point', 'trip_type')},
        ),
    ]
