# Generated by Django 2.0.7 on 2018-07-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20180718_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='trip_type',
            field=models.IntegerField(choices=[(1, 'trip1'), (2, 'trip2')]),
        ),
        migrations.AlterField(
            model_name='requests',
            name='trip_type',
            field=models.IntegerField(choices=[(1, 'trip1'), (2, 'trip2')], default=1),
        ),
    ]
