# Generated by Django 2.0.7 on 2018-07-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20180718_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupshistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
