# Generated by Django 2.0.7 on 2018-07-21 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20180721_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='trip_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
