# Generated by Django 2.0.7 on 2018-07-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_requests_trip_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupshistory',
            name='car',
        ),
        migrations.RemoveField(
            model_name='groupshistory',
            name='owner',
        ),
        migrations.AddField(
            model_name='groupshistory',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rides.Groups'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='trip_type',
            field=models.IntegerField(choices=[(1, 'Enroute'), (2, 'Return')]),
        ),
        migrations.AlterField(
            model_name='requests',
            name='trip_type',
            field=models.IntegerField(choices=[(1, 'Enroute'), (2, 'Return')], default=1),
        ),
    ]
