# Generated by Django 2.0.7 on 2018-07-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_auto_20180722_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='entry_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rides.Points'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='pay_status',
            field=models.IntegerField(choices=[(0, 'no pay'), (1, 'paid')], default=0),
        ),
    ]
