# Generated by Django 2.0.7 on 2018-07-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_auto_20180723_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='trip_time',
        ),
    ]
