# Generated by Django 2.0.7 on 2018-07-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_remove_requests_trip_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='entry_point',
            new_name='point',
        ),
    ]
