# Generated by Django 2.0.7 on 2018-07-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_auto_20180724_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='trip1_intermediate_points',
            field=models.ManyToManyField(default=1, related_name='trip1_intermediate_points', to='rides.Points'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='trip1_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='trip2_intermediate_points',
            field=models.ManyToManyField(default=1, related_name='trip2_intermediate_points', to='rides.Points'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='trip2_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
