# Generated by Django 2.0.7 on 2018-07-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_auto_20180724_1812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cars',
            unique_together={('owner', 'car_number')},
        ),
    ]
