# Generated by Django 2.0.7 on 2018-07-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_auto_20180728_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.Cars', unique=True),
        ),
    ]
