# Generated by Django 2.0.7 on 2018-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_auto_20180728_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_reference',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
