# Generated by Django 2.0.7 on 2018-07-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_users_user_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
