# Generated by Django 2.0.7 on 2018-08-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_auto_20180802_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_status',
            field=models.CharField(choices=[('pending', 'pending'), ('ontrip', 'ontrip'), ('accepted', 'accepted')], default='pending', max_length=10),
        ),
    ]
