# Generated by Django 2.0.7 on 2018-08-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_auto_20180804_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('trip1', 'trip1'), ('trip2', 'trip2')], default='idle', max_length=10),
        ),
    ]
