# Generated by Django 2.0.7 on 2018-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_groups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ride_status',
            field=models.CharField(choices=[('idle', 'idle'), ('trip1', 'trip1'), ('trip2', 'trip2')], default='idle', max_length=25),
        ),
    ]
